export const data = JSON.parse("{\"key\":\"v-13225e36\",\"path\":\"/notes/fe/javascript/Web%20Apis/%E5%85%AD%E3%80%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%20%E7%BB%BC%E5%90%88%E6%A1%88%E4%BE%8B%20%E9%98%B6%E6%AE%B5%E6%A1%88%E4%BE%8B.html\",\"title\":\"六、正则表达式 | 综合案例 | 阶段案例\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"六、正则表达式 | 综合案例 | 阶段案例\",\"order\":6,\"description\":\"正则表达式 用来匹配字符串中字符组合的模式。在JS中，正则表达式也是对象。 通常用来查找、替换那些符合正则表达式的文本。 语法 1. 定义正则表达式语法 语法： const 变量名 = /表达式/ 示例： ```js const reg = /前端/ ``` 2. 判断是否有符合规则的字符串 test() 方法：用来查看正则表达式与指定的字符串是否匹配...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/notes/fe/javascript/Web%20Apis/%E5%85%AD%E3%80%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%20%E7%BB%BC%E5%90%88%E6%A1%88%E4%BE%8B%20%E9%98%B6%E6%AE%B5%E6%A1%88%E4%BE%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"A.M. Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"六、正则表达式 | 综合案例 | 阶段案例\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"正则表达式 用来匹配字符串中字符组合的模式。在JS中，正则表达式也是对象。 通常用来查找、替换那些符合正则表达式的文本。 语法 1. 定义正则表达式语法 语法： const 变量名 = /表达式/ 示例： ```js const reg = /前端/ ``` 2. 判断是否有符合规则的字符串 test() 方法：用来查看正则表达式与指定的字符串是否匹配...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Arrow Magician\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"六、正则表达式 | 综合案例 | 阶段案例\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Arrow Magician\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"正则表达式\",\"slug\":\"正则表达式\",\"link\":\"#正则表达式\",\"children\":[{\"level\":3,\"title\":\"语法\",\"slug\":\"语法\",\"link\":\"#语法\",\"children\":[]},{\"level\":3,\"title\":\"元字符\",\"slug\":\"元字符\",\"link\":\"#元字符\",\"children\":[]},{\"level\":3,\"title\":\"修饰符\",\"slug\":\"修饰符\",\"link\":\"#修饰符\",\"children\":[]}]},{\"level\":2,\"title\":\"综合案例 - 小兔鲜页面注册\",\"slug\":\"综合案例-小兔鲜页面注册\",\"link\":\"#综合案例-小兔鲜页面注册\",\"children\":[{\"level\":3,\"title\":\"业务模块\",\"slug\":\"业务模块\",\"link\":\"#业务模块\",\"children\":[]},{\"level\":3,\"title\":\"需求分析\",\"slug\":\"需求分析\",\"link\":\"#需求分析\",\"children\":[]},{\"level\":3,\"title\":\"代码编写\",\"slug\":\"代码编写\",\"link\":\"#代码编写\",\"children\":[]}]},{\"level\":2,\"title\":\"阶段案例\",\"slug\":\"阶段案例\",\"link\":\"#阶段案例\",\"children\":[{\"level\":3,\"title\":\"小兔鲜登录页面\",\"slug\":\"小兔鲜登录页面\",\"link\":\"#小兔鲜登录页面\",\"children\":[]},{\"level\":3,\"title\":\"小兔鲜首页\",\"slug\":\"小兔鲜首页\",\"link\":\"#小兔鲜首页\",\"children\":[]}]}],\"readingTime\":{\"minutes\":13.08,\"words\":3925},\"filePathRelative\":\"notes/fe/javascript/Web Apis/六、正则表达式 综合案例 阶段案例.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
