export const data = JSON.parse("{\"key\":\"v-61a1265b\",\"path\":\"/notes/fe/javascript/Web%20Apis/%E6%AF%8F%E6%97%A5%E4%BD%9C%E4%B8%9A%20-%202.html\",\"title\":\"每日作业 - 2\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"每日作业 - 2\",\"order\":9,\"description\":\"01 - 点击随机显示图片 思路： 1. 先拿到按钮和图片 2. 给按钮注册点击事件 3. 获取数组长度的随机数 4. 把数组里面的随机数，就是数组里面的图片地址复制给img的src里面。 代码编写 ```html let arr = ['images/1.jpg', 'images/01.gif', 'images/02.gif'] function...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/Blog/notes/fe/javascript/Web%20Apis/%E6%AF%8F%E6%97%A5%E4%BD%9C%E4%B8%9A%20-%202.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"A.M. Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"每日作业 - 2\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"01 - 点击随机显示图片 思路： 1. 先拿到按钮和图片 2. 给按钮注册点击事件 3. 获取数组长度的随机数 4. 把数组里面的随机数，就是数组里面的图片地址复制给img的src里面。 代码编写 ```html let arr = ['images/1.jpg', 'images/01.gif', 'images/02.gif'] function...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Arrow Magician\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"每日作业 - 2\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Arrow Magician\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"01 -  点击随机显示图片\",\"slug\":\"_01-点击随机显示图片\",\"link\":\"#_01-点击随机显示图片\",\"children\":[{\"level\":3,\"title\":\"思路：\",\"slug\":\"思路\",\"link\":\"#思路\",\"children\":[]},{\"level\":3,\"title\":\"代码编写\",\"slug\":\"代码编写\",\"link\":\"#代码编写\",\"children\":[]}]},{\"level\":2,\"title\":\"02 - 同意协议\",\"slug\":\"_02-同意协议\",\"link\":\"#_02-同意协议\",\"children\":[{\"level\":3,\"title\":\"思路\",\"slug\":\"思路-1\",\"link\":\"#思路-1\",\"children\":[]},{\"level\":3,\"title\":\"代码编写\",\"slug\":\"代码编写-1\",\"link\":\"#代码编写-1\",\"children\":[]}]},{\"level\":2,\"title\":\"03 - 验证码倒计时\",\"slug\":\"_03-验证码倒计时\",\"link\":\"#_03-验证码倒计时\",\"children\":[{\"level\":3,\"title\":\"思路\",\"slug\":\"思路-2\",\"link\":\"#思路-2\",\"children\":[]},{\"level\":3,\"title\":\"代码编写\",\"slug\":\"代码编写-2\",\"link\":\"#代码编写-2\",\"children\":[]}]},{\"level\":2,\"title\":\"04 - 显示隐藏密码\",\"slug\":\"_04-显示隐藏密码\",\"link\":\"#_04-显示隐藏密码\",\"children\":[{\"level\":3,\"title\":\"思路\",\"slug\":\"思路-3\",\"link\":\"#思路-3\",\"children\":[]},{\"level\":3,\"title\":\"代码编写\",\"slug\":\"代码编写-3\",\"link\":\"#代码编写-3\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.01,\"words\":602},\"filePathRelative\":\"notes/fe/javascript/Web Apis/每日作业 - 2.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
