export const data = JSON.parse("{\"key\":\"v-156395d6\",\"path\":\"/notes/fe/javascript/JavaScript%20%E8%BF%9B%E9%98%B6/%E4%BD%9C%E4%B8%9A%20-%202.html\",\"title\":\"作业 - 2\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"作业 - 2\",\"order\":6,\"description\":\"客观题 https://ks.wjx.top/vj/QG54lSj.aspx 排错题 1. forEach排错题 以下代码是否有问题，如果有，如何修改 ```js const arr = [1,2,3,4,5] const res = arr.forEach(item,index, arr) { console.log(item); } ``` 答：f...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/Blog/notes/fe/javascript/JavaScript%20%E8%BF%9B%E9%98%B6/%E4%BD%9C%E4%B8%9A%20-%202.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"A.M. Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"作业 - 2\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"客观题 https://ks.wjx.top/vj/QG54lSj.aspx 排错题 1. forEach排错题 以下代码是否有问题，如果有，如何修改 ```js const arr = [1,2,3,4,5] const res = arr.forEach(item,index, arr) { console.log(item); } ``` 答：f...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Arrow Magician\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"作业 - 2\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Arrow Magician\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"客观题\",\"slug\":\"客观题\",\"link\":\"#客观题\",\"children\":[]},{\"level\":2,\"title\":\"排错题\",\"slug\":\"排错题\",\"link\":\"#排错题\",\"children\":[{\"level\":3,\"title\":\"1. forEach排错题\",\"slug\":\"_1-foreach排错题\",\"link\":\"#_1-foreach排错题\",\"children\":[]},{\"level\":3,\"title\":\"2. 实例成员 - 静态成员\",\"slug\":\"_2-实例成员-静态成员\",\"link\":\"#_2-实例成员-静态成员\",\"children\":[]},{\"level\":3,\"title\":\"3. map 的排错题\",\"slug\":\"_3-map-的排错题\",\"link\":\"#_3-map-的排错题\",\"children\":[]},{\"level\":3,\"title\":\"4. find 排错题\",\"slug\":\"_4-find-排错题\",\"link\":\"#_4-find-排错题\",\"children\":[]},{\"level\":3,\"title\":\"5. 字符串的 subString 排错题\",\"slug\":\"_5-字符串的-substring-排错题\",\"link\":\"#_5-字符串的-substring-排错题\",\"children\":[]}]},{\"level\":2,\"title\":\"主观题\",\"slug\":\"主观题\",\"link\":\"#主观题\",\"children\":[{\"level\":3,\"title\":\"需求\",\"slug\":\"需求\",\"link\":\"#需求\",\"children\":[]},{\"level\":3,\"title\":\"代码\",\"slug\":\"代码\",\"link\":\"#代码\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.22,\"words\":666},\"filePathRelative\":\"notes/fe/javascript/JavaScript 进阶/作业 - 2.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
