export const data = JSON.parse("{\"key\":\"v-55a17b04\",\"path\":\"/notes/fe/javascript/JavaScript%20%E5%9F%BA%E7%A1%80/%E5%9B%9B%E3%80%81%E5%87%BD%E6%95%B0%20%E7%BB%BC%E5%90%88%E6%A1%88%E4%BE%8B.html\",\"title\":\"四、函数 | 综合案例\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"四、函数 | 综合案例\",\"order\":4,\"description\":\"函数 自我感觉，如果是根据知识路线的方式来学习的话，这个阶段对函数的概念确实模糊。不能理解，可以结合这个文档 (./函数分组引发的思考)看视频 (https://www.bilibili.com/video/BV1MM41197xm/?spmidfrom=333.1007.toprightbarwindowcustomcollection.conten...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/notes/fe/javascript/JavaScript%20%E5%9F%BA%E7%A1%80/%E5%9B%9B%E3%80%81%E5%87%BD%E6%95%B0%20%E7%BB%BC%E5%90%88%E6%A1%88%E4%BE%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"A.M. Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"四、函数 | 综合案例\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"函数 自我感觉，如果是根据知识路线的方式来学习的话，这个阶段对函数的概念确实模糊。不能理解，可以结合这个文档 (./函数分组引发的思考)看视频 (https://www.bilibili.com/video/BV1MM41197xm/?spmidfrom=333.1007.toprightbarwindowcustomcollection.conten...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Arrow Magician\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"四、函数 | 综合案例\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Arrow Magician\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"函数\",\"slug\":\"函数\",\"link\":\"#函数\",\"children\":[{\"level\":3,\"title\":\"什么是函数？\",\"slug\":\"什么是函数\",\"link\":\"#什么是函数\",\"children\":[]},{\"level\":3,\"title\":\"函数的使用\",\"slug\":\"函数的使用\",\"link\":\"#函数的使用\",\"children\":[]},{\"level\":3,\"title\":\"函数传参\",\"slug\":\"函数传参\",\"link\":\"#函数传参\",\"children\":[]},{\"level\":3,\"title\":\"函数返回值\",\"slug\":\"函数返回值\",\"link\":\"#函数返回值\",\"children\":[]},{\"level\":3,\"title\":\"作用域\",\"slug\":\"作用域\",\"link\":\"#作用域\",\"children\":[]},{\"level\":3,\"title\":\"匿名函数\",\"slug\":\"匿名函数\",\"link\":\"#匿名函数\",\"children\":[]}]},{\"level\":2,\"title\":\"综合案例\",\"slug\":\"综合案例\",\"link\":\"#综合案例\",\"children\":[{\"level\":3,\"title\":\"需求\",\"slug\":\"需求\",\"link\":\"#需求\",\"children\":[]},{\"level\":3,\"title\":\"分析\",\"slug\":\"分析\",\"link\":\"#分析\",\"children\":[]},{\"level\":3,\"title\":\"代码编写\",\"slug\":\"代码编写\",\"link\":\"#代码编写\",\"children\":[]}]},{\"level\":2,\"title\":\"补充知识\",\"slug\":\"补充知识\",\"link\":\"#补充知识\",\"children\":[{\"level\":3,\"title\":\"逻辑中断\",\"slug\":\"逻辑中断\",\"link\":\"#逻辑中断\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.41,\"words\":1324},\"filePathRelative\":\"notes/fe/javascript/JavaScript 基础/四、函数 综合案例.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
